COOKIE_NAME = 'searx'
ENDPOINT_NAME = 'searx.css'
HTML_TAG_REPLACE = '(<div id="pagination">)|(<head>)'
JAIL_PATH = '/tmp'
MAX_RETRY = 5
PORT = 3000
TARGET = '127.0.0.1:8888'
TIMEOUT_LOAD = 120
WHITELIST = ['8.8.8.8', '1.1.1.1', '176.31.252.227', '2001:41d0:8:de3::1']

[WHITELIST_PAGES]
GET = ['^/$', '^/autocompleter(.*)$', '^/favicon.ico$', '^/about$', '^/robots.txt$', '^/opensearch.xml$']
POST = ['^/preferences$']
