COOKIE_NAME = 'vf'
ENDPOINT_NAME = 'searx.css'
HTML_TAG_REPLACE = '(<div id="pagination">)|(<head>)'
JAIL_PATH = '/tmp'
MAX_RETRY = 5
PORT = 3000
TARGET = '127.0.0.1:8888'
TIMEOUT_LOAD = 120
WHITELIST = ['8.8.8.8', '1.1.1.1']

[WHITELIST_PAGES]
GET = ['^/$', '^/autocompleter(.*)$', '^/favicon.ico$', '^/about$', '^/robots.txt$', '^/opensearch.xml$', '^/image_proxy(.*)$']
POST = ['^/preferences$']